import type { AppConfig, Tweet } from "./types";

export const DROPPABLE_FILTER_REASONS = new Set([
  "block_pattern:location_hashtags_link_only",
  "block_pattern:location_word_soup_link",
  "block_pattern:suspicious_location_link",
  "block_pattern:generated_location_link_campaign",
  "block_pattern:luleburgaz_short_link_campaign",
  "block_pattern:luleburgaz_ad_profile",
  "block_pattern:luleburgaz_location_dump",
]);

const LULEBURGAZ_CAMPAIGN_LOCATION_TERMS = [
  "çorlu",
  "corlu",
  "çerkezköy",
  "cerkezkoy",
  "şarkköy",
  "sarkkoy",
  "malkara",
  "hayrabolu",
  "saray",
  "ergene",
  "muratlı",
  "muratli",
  "marmaraereğlisi",
  "marmaraereglisi",
];
const LULEBURGAZ_CAMPAIGN_PROFILE_TERMS = ["bayan", "escort", "eskort"];

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function compactText(value: string): string {
  return value.normalize("NFKC").toLowerCase().replace(/[^\p{L}\p{N}]/gu, "");
}

function textContainsTerm(haystackLower: string, haystackCompact: string, term: string): boolean {
  const cleaned = term.trim().toLowerCase();
  return Boolean(cleaned) &&
    (haystackLower.includes(cleaned) || haystackCompact.includes(compactText(cleaned)));
}

function extractHashtags(text: string): string[] {
  return [...text.matchAll(/#([^\s#@/]+)/gu)].map((match) => match[1].toLowerCase());
}

function meaningfulTextLength(text: string): number {
  return compactText(
    text
      .replace(/https?:\/\/\S+/giu, " ")
      .replace(/@\S+/gu, " ")
      .replace(/#\S+/gu, " "),
  ).length;
}

function containsLocation(text: string, term: string): boolean {
  const pattern = new RegExp(
    `(?:^|[^\\p{L}\\p{N}_])#?${escapeRegex(term)}(?=$|[^\\p{L}\\p{N}_])`,
    "iu",
  );
  return pattern.test(text);
}

function countLocationMentions(text: string, locationTerms: Set<string>): number {
  let count = 0;
  for (const term of locationTerms) {
    if (term && containsLocation(text, term)) count += 1;
  }
  return count;
}

function looksLikeAutogeneratedHandle(handle: string): boolean {
  const cleaned = handle.trim();
  return !cleaned.includes("_") && /^[A-Za-z]{5,}[A-Za-z]*\d+[A-Za-z0-9]*$/.test(cleaned);
}

function isLuleburgazQuery(query: string): boolean {
  const compact = compactText(query);
  return compact === "lüleburgaz" || compact === "luleburgaz";
}

function looksLikeGeneratedNumericHandle(handle: string): boolean {
  return /^[A-Za-z]{3,}\d{6,}$/.test(handle.trim());
}

function containsPictographicSymbol(text: string): boolean {
  return /\p{Extended_Pictographic}/u.test(text);
}

function looksLikeSimpleDisplayName(name: string): boolean {
  const cleaned = name.trim();
  return cleaned.length >= 3 && /^\p{L}+$/u.test(cleaned);
}

function countNonLocationWords(text: string, locationTerms: Set<string>): number {
  let remaining = text.replace(/https?:\/\/\S+/giu, " ").replace(/@\S+/gu, " ");
  const sortedTerms = [...locationTerms].sort((left, right) => right.length - left.length);
  for (const term of sortedTerms) {
    if (!term) continue;
    const pattern = new RegExp(
      `(?:^|[^\\p{L}\\p{N}_])#?${escapeRegex(term)}(?=$|[^\\p{L}\\p{N}_])`,
      "giu",
    );
    remaining = remaining.replace(pattern, " ");
  }
  return remaining.match(/\p{L}+/gu)?.length ?? 0;
}

function queryBypassesFilter(config: AppConfig, query: string): boolean {
  const normalized = query.trim().toLowerCase();
  if (normalized.startsWith("from:")) return true;
  return config.tweetFilterBypassQueries.some(
    (candidate) => candidate.trim().toLowerCase() === normalized,
  );
}

export function evaluateTweetFilter(config: AppConfig, query: string, tweet: Tweet): string[] {
  if (config.tweetFilterMode === "off" || queryBypassesFilter(config, query)) return [];

  const haystack = [tweet.text, tweet.userHandle, tweet.userName, tweet.link].join(" ");
  const haystackLower = haystack.toLowerCase();
  const haystackCompact = compactText(haystack);
  const reasons: string[] = [];

  for (const term of config.blockedTweetTerms) {
    const cleaned = term.trim().toLowerCase();
    if (textContainsTerm(haystackLower, haystackCompact, cleaned)) {
      reasons.push(`blocked_term:${cleaned}`);
    }
  }
  for (const term of config.watchTweetTerms) {
    const cleaned = term.trim().toLowerCase();
    if (textContainsTerm(haystackLower, haystackCompact, cleaned)) {
      reasons.push(`watch_term:${cleaned}`);
    }
  }

  const hashtags = extractHashtags(tweet.text);
  const locationTerms = new Set(config.locationHashtagTerms.map((term) => term.toLowerCase()));
  const locationHashtags = hashtags.filter((tag) => locationTerms.has(tag));
  const hasLink = /https?:\/\//iu.test(tweet.text);
  const meaningfulLength = meaningfulTextLength(tweet.text);

  if (hasLink && hashtags.length >= 2 && locationHashtags.length >= 1 && meaningfulLength <= 4) {
    reasons.push("block_pattern:location_hashtags_link_only");
  }

  const locationMentions = countLocationMentions(tweet.text, locationTerms);
  if (hasLink && locationMentions >= 3 && meaningfulLength <= 45) {
    reasons.push("block_pattern:location_word_soup_link");
  }
  if (
    hasLink &&
    locationMentions >= 2 &&
    meaningfulLength <= 90 &&
    looksLikeAutogeneratedHandle(tweet.userHandle)
  ) {
    reasons.push("block_pattern:suspicious_location_link");
  }

  if (
    hasLink &&
    locationMentions >= 1 &&
    looksLikeGeneratedNumericHandle(tweet.userHandle) &&
    looksLikeSimpleDisplayName(tweet.userName) &&
    countNonLocationWords(tweet.text, locationTerms) <= 5 &&
    containsPictographicSymbol(tweet.text)
  ) {
    reasons.push("block_pattern:generated_location_link_campaign");
  }

  if (isLuleburgazQuery(query) && hasLink) {
    const shortCampaignHandle = looksLikeGeneratedNumericHandle(tweet.userHandle);
    const profileCampaignHandle =
      shortCampaignHandle || looksLikeAutogeneratedHandle(tweet.userHandle);
    const campaignLocationTerms = new Set([
      ...locationTerms,
      ...LULEBURGAZ_CAMPAIGN_LOCATION_TERMS,
    ]);
    const campaignLocationMentions = countLocationMentions(
      tweet.text,
      campaignLocationTerms,
    );
    const remainingWords = countNonLocationWords(tweet.text, campaignLocationTerms);

    if (
      shortCampaignHandle &&
      campaignLocationMentions >= 1 &&
      remainingWords <= 3 &&
      looksLikeSimpleDisplayName(tweet.userName)
    ) {
      reasons.push("block_pattern:luleburgaz_short_link_campaign");
    }

    const profile = `${tweet.userHandle} ${tweet.userName}`.toLowerCase();
    if (
      profileCampaignHandle &&
      campaignLocationMentions >= 1 &&
      LULEBURGAZ_CAMPAIGN_PROFILE_TERMS.some((term) => profile.includes(term))
    ) {
      reasons.push("block_pattern:luleburgaz_ad_profile");
    }
    if (profileCampaignHandle && campaignLocationMentions >= 3 && countChar(tweet.text, ",") >= 5) {
      reasons.push("block_pattern:luleburgaz_location_dump");
    }
  }

  if (/(?:\+?90\s*)?0?5\d{2}[\s.-]?\d{3}[\s.-]?\d{2}[\s.-]?\d{2}/u.test(tweet.text)) {
    reasons.push("watch_pattern:phone_number");
  }
  return [...new Set(reasons)];
}

function countChar(value: string, character: string): number {
  return [...value].filter((item) => item === character).length;
}

export function shouldDropTweet(reasons: string[]): boolean {
  return reasons.some(
    (reason) => reason.startsWith("blocked_term:") || DROPPABLE_FILTER_REASONS.has(reason),
  );
}
