import type { AppConfig, Tweet } from "./types";

export const DROPPABLE_FILTER_REASONS = new Set([
  "required_prefix_missing",
  "block_pattern:location_hashtags_link_only",
  "block_pattern:location_word_soup_link",
  "block_pattern:suspicious_location_link",
  "block_pattern:generated_location_link_campaign",
  "block_pattern:generated_name_location_link_campaign",
  "block_pattern:trakya_location_word_campaign",
  "block_pattern:trakya_location_dump_ad_campaign",
  "block_pattern:luleburgaz_short_link_campaign",
  "block_pattern:luleburgaz_ad_profile",
  "block_pattern:luleburgaz_location_dump",
]);

const LULEBURGAZ_CAMPAIGN_LOCATION_TERMS = [
  "çorlu",
  "corlu",
  "çerkezköy",
  "cerkezkoy",
  "şarkköy",
  "sarkkoy",
  "malkara",
  "hayrabolu",
  "saray",
  "ergene",
  "muratlı",
  "muratli",
  "marmaraereğlisi",
  "marmaraereglisi",
];
const LULEBURGAZ_CAMPAIGN_PROFILE_TERMS = ["bayan", "escort", "eskort"];
const TRAKYA_LOCATION_CAMPAIGN_TERMS = [
  "kırklareli",
  "kirklareli",
  "edirne",
  "havsa",
  "kapıkule",
  "kapikule",
];

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function compactText(value: string): string {
  return value.normalize("NFKC").toLowerCase().replace(/[^\p{L}\p{N}]/gu, "");
}

function textContainsTerm(haystackLower: string, haystackCompact: string, term: string): boolean {
  const cleaned = term.trim().toLowerCase();
  return Boolean(cleaned) &&
    (haystackLower.includes(cleaned) || haystackCompact.includes(compactText(cleaned)));
}

function extractHashtags(text: string): string[] {
  return [...text.matchAll(/#([^\s#@/]+)/gu)].map((match) => match[1].toLowerCase());
}

function meaningfulTextLength(text: string): number {
  return compactText(
    text
      .replace(/https?:\/\/\S+/giu, " ")
      .replace(/@\S+/gu, " ")
      .replace(/#\S+/gu, " "),
  ).length;
}

function containsLocation(text: string, term: string): boolean {
  const pattern = new RegExp(
    `(?:^|[^\\p{L}\\p{N}_])#?${escapeRegex(term)}(?=$|[^\\p{L}\\p{N}_])`,
    "iu",
  );
  return pattern.test(text);
}

function countLocationMentions(text: string, locationTerms: Set<string>): number {
  let count = 0;
  for (const term of locationTerms) {
    if (term && containsLocation(text, term)) count += 1;
  }
  return count;
}

function looksLikeAutogeneratedHandle(handle: string): boolean {
  const cleaned = handle.trim();
  return !cleaned.includes("_") && /^[A-Za-z]{5,}[A-Za-z]*\d+[A-Za-z0-9]*$/.test(cleaned);
}

function comparableName(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/\p{M}/gu, "")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");
}

function looksLikeGeneratedNameHandle(handle: string, displayName: string): boolean {
  const rawHandle = handle.trim();
  const nameParts = displayName
    .trim()
    .split(/\s+/u)
    .map(comparableName)
    .filter(Boolean);
  if (
    rawHandle.includes("_") ||
    !/^[A-Za-z0-9]{8,24}$/.test(rawHandle) ||
    nameParts.length !== 2
  ) {
    return false;
  }
  const normalizedHandle = comparableName(rawHandle);
  const normalizedName = nameParts.join("");
  let commonPrefix = 0;
  while (
    commonPrefix < normalizedHandle.length &&
    commonPrefix < normalizedName.length &&
    normalizedHandle[commonPrefix] === normalizedName[commonPrefix]
  ) {
    commonPrefix += 1;
  }
  const minimumPrefix = Math.min(normalizedName.length, Math.max(8, nameParts[0].length + 1));
  const randomSuffix = normalizedHandle.slice(commonPrefix);
  return commonPrefix >= minimumPrefix &&
    randomSuffix.length >= 2 &&
    randomSuffix.length <= 4 &&
    !/^\d+$/.test(randomSuffix);
}

function looksLikeGeneratedCampaignProfile(handle: string, displayName: string): boolean {
  const simpleFullName = /^\p{L}+(?:\s+\p{L}+)+$/u.test(displayName.trim());
  return simpleFullName &&
    (looksLikeGeneratedNameHandle(handle, displayName) || /\d{5}$/.test(handle.trim()));
}

function isLuleburgazQuery(query: string): boolean {
  const compact = compactText(query);
  return compact === "lüleburgaz" || compact === "luleburgaz";
}

function looksLikeGeneratedNumericHandle(handle: string): boolean {
  return /^[A-Za-z]{3,}\d{6,}$/.test(handle.trim());
}

function containsPictographicSymbol(text: string): boolean {
  return /\p{Extended_Pictographic}/u.test(text);
}

function looksLikeSimpleDisplayName(name: string): boolean {
  const cleaned = name.trim();
  return cleaned.length >= 3 && /^\p{L}+$/u.test(cleaned);
}

function countNonLocationWords(text: string, locationTerms: Set<string>): number {
  let remaining = text.replace(/https?:\/\/\S+/giu, " ").replace(/@\S+/gu, " ");
  const sortedTerms = [...locationTerms].sort((left, right) => right.length - left.length);
  for (const term of sortedTerms) {
    if (!term) continue;
    const pattern = new RegExp(
      `(?:^|[^\\p{L}\\p{N}_])#?${escapeRegex(term)}(?=$|[^\\p{L}\\p{N}_])`,
      "giu",
    );
    remaining = remaining.replace(pattern, " ");
  }
  return remaining.match(/\p{L}+/gu)?.length ?? 0;
}

function queryBypassesFilter(config: AppConfig, query: string): boolean {
  const normalized = query.trim().toLowerCase();
  if (normalized.startsWith("from:")) return true;
  return config.tweetFilterBypassQueries.some(
    (candidate) => candidate.trim().toLowerCase() === normalized,
  );
}

export function evaluateTweetFilter(config: AppConfig, query: string, tweet: Tweet): string[] {
  const reasons: string[] = [];
  const requiredPrefix = config.tweetRequiredPrefixes[query.trim().toLowerCase()];
  if (requiredPrefix) {
    const normalizedText = tweet.text.normalize("NFKC").trimStart().toLocaleUpperCase("tr-TR");
    const normalizedPrefix = requiredPrefix.normalize("NFKC").toLocaleUpperCase("tr-TR");
    if (!normalizedText.startsWith(normalizedPrefix)) {
      reasons.push("required_prefix_missing");
    }
  }
  if (config.tweetFilterMode === "off" || queryBypassesFilter(config, query)) return reasons;

  const normalizedHandle = tweet.userHandle.trim().replace(/^@/, "").toLowerCase();
  if (config.blockedTweetHandles.includes(normalizedHandle)) {
    reasons.push(`blocked_handle:${normalizedHandle}`);
  }

  const haystack = [tweet.text, tweet.userHandle, tweet.userName, tweet.link].join(" ");
  const haystackLower = haystack.toLowerCase();
  const haystackCompact = compactText(haystack);
  for (const term of config.blockedTweetTerms) {
    const cleaned = term.trim().toLowerCase();
    if (textContainsTerm(haystackLower, haystackCompact, cleaned)) {
      reasons.push(`blocked_term:${cleaned}`);
    }
  }
  for (const term of config.watchTweetTerms) {
    const cleaned = term.trim().toLowerCase();
    if (textContainsTerm(haystackLower, haystackCompact, cleaned)) {
      reasons.push(`watch_term:${cleaned}`);
    }
  }

  const hashtags = extractHashtags(tweet.text);
  const locationTerms = new Set(config.locationHashtagTerms.map((term) => term.toLowerCase()));
  const locationHashtags = hashtags.filter((tag) => locationTerms.has(tag));
  const hasLink = /https?:\/\//iu.test(tweet.text);
  const meaningfulLength = meaningfulTextLength(tweet.text);

  if (hasLink && hashtags.length >= 2 && locationHashtags.length >= 1 && meaningfulLength <= 4) {
    reasons.push("block_pattern:location_hashtags_link_only");
  }

  const locationMentions = countLocationMentions(tweet.text, locationTerms);
  if (hasLink && locationMentions >= 3 && meaningfulLength <= 45) {
    reasons.push("block_pattern:location_word_soup_link");
  }
  if (
    hasLink &&
    locationMentions >= 2 &&
    meaningfulLength <= 90 &&
    looksLikeAutogeneratedHandle(tweet.userHandle)
  ) {
    reasons.push("block_pattern:suspicious_location_link");
  }

  if (
    hasLink &&
    locationMentions >= 1 &&
    looksLikeGeneratedNumericHandle(tweet.userHandle) &&
    looksLikeSimpleDisplayName(tweet.userName) &&
    countNonLocationWords(tweet.text, locationTerms) <= 5 &&
    containsPictographicSymbol(tweet.text)
  ) {
    reasons.push("block_pattern:generated_location_link_campaign");
  }
  if (
    hasLink &&
    locationMentions >= 1 &&
    countNonLocationWords(tweet.text, locationTerms) <= 3 &&
    containsPictographicSymbol(tweet.text) &&
    looksLikeGeneratedNameHandle(tweet.userHandle, tweet.userName)
  ) {
    reasons.push("block_pattern:generated_name_location_link_campaign");
  }
  const trakyaCampaignMentions = countLocationMentions(
    tweet.text,
    new Set(TRAKYA_LOCATION_CAMPAIGN_TERMS),
  );
  if (
    hasLink &&
    trakyaCampaignMentions >= 4 &&
    containsPictographicSymbol(tweet.text) &&
    looksLikeGeneratedCampaignProfile(tweet.userHandle, tweet.userName)
  ) {
    reasons.push("block_pattern:trakya_location_word_campaign");
  }

  const campaignLocationTerms = new Set([
    ...locationTerms,
    ...LULEBURGAZ_CAMPAIGN_LOCATION_TERMS,
  ]);
  const campaignLocationMentions = countLocationMentions(
    tweet.text,
    campaignLocationTerms,
  );
  const profile = `${tweet.userHandle} ${tweet.userName}`.toLowerCase();
  const campaignText = tweet.text.toLowerCase();
  const hasCampaignProfileTerm = LULEBURGAZ_CAMPAIGN_PROFILE_TERMS.some(
    (term) => profile.includes(term) || campaignText.includes(term),
  );
  if (
    hasLink &&
    campaignLocationMentions >= 8 &&
    countChar(tweet.text, ",") >= 8 &&
    hasCampaignProfileTerm &&
    containsPictographicSymbol(tweet.text)
  ) {
    reasons.push("block_pattern:trakya_location_dump_ad_campaign");
  }

  if (isLuleburgazQuery(query) && hasLink) {
    const shortCampaignHandle = looksLikeGeneratedNumericHandle(tweet.userHandle);
    const profileCampaignHandle =
      shortCampaignHandle || looksLikeAutogeneratedHandle(tweet.userHandle);
    const remainingWords = countNonLocationWords(tweet.text, campaignLocationTerms);
    if (
      shortCampaignHandle &&
      campaignLocationMentions >= 1 &&
      remainingWords <= 3 &&
      looksLikeSimpleDisplayName(tweet.userName)
    ) {
      reasons.push("block_pattern:luleburgaz_short_link_campaign");
    }

    if (
      profileCampaignHandle &&
      campaignLocationMentions >= 1 &&
      hasCampaignProfileTerm
    ) {
      reasons.push("block_pattern:luleburgaz_ad_profile");
    }
    if (
      campaignLocationMentions >= 5 &&
      countChar(tweet.text, ",") >= 5 &&
      hasCampaignProfileTerm
    ) {
      reasons.push("block_pattern:luleburgaz_location_dump");
    }
    if (profileCampaignHandle && campaignLocationMentions >= 3 && countChar(tweet.text, ",") >= 5) {
      reasons.push("block_pattern:luleburgaz_location_dump");
    }
  }

  if (/(?:\+?90\s*)?0?5\d{2}[\s.-]?\d{3}[\s.-]?\d{2}[\s.-]?\d{2}/u.test(tweet.text)) {
    reasons.push("watch_pattern:phone_number");
  }
  return [...new Set(reasons)];
}

function countChar(value: string, character: string): number {
  return [...value].filter((item) => item === character).length;
}

export function shouldDropTweet(reasons: string[]): boolean {
  return reasons.some(
    (reason) =>
      reason.startsWith("blocked_term:") ||
      reason.startsWith("blocked_handle:") ||
      DROPPABLE_FILTER_REASONS.has(reason),
  );
}
